import Vue from 'vue'

const names = {
  "hussar-todoList":{
    "title":"待办任务",
    "selectProcess":"请选择流程",
    "taskContent":"任务内容",
    "sender":"发送人",
    "handler":"办理人",
    "selectSender":"选择发送人",
    "process":"流程名称",
    "node":"节点名称",
    "creationTime":"创建时间",
    "requestFail":"请求下拉框数据失败！",
    "notStarted":"工作流服务未启动！",
    "selectOne":"请选择一位用户！",
    "title2":"已办任务",
    "withdrawal":"撤回",
    "urging":"催办",
    "withdrawing":"正在撤回",
    "withdrawalSuccessful":"撤回成功！",
    "urgingSuccess":"催办成功！",
    "error":"撤回失败！",
    "当前节点不能撤回":"当前节点不能撤回！",
    "流程实例id为空":"流程实例id为空！",
    "流程已经结束，无法催办":"流程已经结束，无法催办！",
    "title3":"我的催办",
    "urgingTime":"催办时间",
    "title4":"我的抄送",
    "ccTime":"抄送时间",
    "title5":"我的委托",
    "assignee":"被委托人",
    "status":"状态",
    "disable":"禁用",
    "enable":"启用",
    "newDelegation":"新增委托",
    "editDelegation":"修改委托",
    "启用成功！":"启用成功！",
    "启用失败！":"启用失败！",
    "禁用成功！":"禁用成功！",
    "禁用失败！":"禁用失败！",
    "此流程已有委托人！":"此流程已有委托人！",
    "保存失败！":"保存失败！",
    "selectTime":"请选择委托时间",
    "selectClient":"请选择被委托人",
    "selectDelegation":"请选择委托流程",
    "selectDelegationNode":"请选择委托节点",
    "commissionProcess":"委托流程",
    "client":"委托人",
    "commissionTime":"委托时间",
    "startDate":"开始日期",
    "endDate":"结束日期",
    "delegateNode": "委托节点",
    "messageType" : "消息提醒方式",
    "allNode": "全部",
    "partialNode": "部分节点",
    "isTransferTask": "是否移交待办",
    "entrustToDo": "委托待办",
    "entrustDone": "委托已办",
    "reTransfer": "收回",
    "reTransferSuccessful":"收回成功！",
  },

  'hussar-common': {
    'search': '查询',
    'deleteSuccessful':'删除成功',
    "startTime":"开始时间",
    "endTime":"结束时间",
    'reset': '重置',
    'new': '新增',
    'delete': '删除',
    'sureUpdate':'确认修改',
    'change': '修改',
    'edit': '编辑',
    'maintenance': '维护',
    'confirm': '确定',
    'save': '保存',
    'cancel': '取消',
    'operation': '操作',
    'operation Successful': '操作成功',
    'saveSuccessful': '保存成功',
    'saveUnsSuccessful': '保存失败',
    'changedSuccessful': '修改成功',
    'changedUnsuccessful': '修改失败',
    'selectOneRecord': '请至少选择一条数据',
    'confirmedToDelete': '确定要删除吗？',
    'notice': '提示',
    'loading': '数据加载中',
    'no data available': '暂无数据',
    'no': '序号',
    'error': '请求数据失败',
    'query': '输入关键字进行过滤',
    'export': '导出',
    'import': '导入',
    'yes': '是',
    'no1': '否',
    'exportError': '导出失败'
  },
  'hussar-bpmCommon': {
    'zh': '中文',
    'en': '英文',
    'success': '成功',
    /* 画布*/
    'componentParameters': '组件参数',
    'nodeID': '节点ID',
    'nodeName': '节点名称',
    'additionalManualActivity': '追加人工活动',
    'appendSingleGateway': '追加单一网关',
    'additionalEnd': '追加结束',
    'additionalAttachment': '追加连线',
    'description': '描述',
    'noConf': '暂未配置',
    'yesConf': '已配置',
    'delSuccess': '删除成功',
    'delFail': '删除失败！',
    'pwdEmpty': '密码不能为空'
  },
  'hussar-navbar': {
    'title': '工作流平台',
    'changePwd': '修改密码',
    'cancel': '取消',
    'determine': '确定',
    'exit': '退出账号',
    'oldPwd': '原密码',
    'enterOld': '请输入原密码',
    'newPwd': '新密码',
    'enterNew': '请输入新密码',
    'noEmpty': '密码不能为空',
    'rule': '密码必须是6-16位非空字符',
    'doExit': '确定要退出吗？',
    'tip': '提示',
    'passWrong': '原密码输入错误！'
  },
  'hussar-login': {
    'hello': '你好！',
    'welcome': '欢迎来到工作流平台！',
    'login': '登录',
    'user': '请输入用户名',
    'pwd': '请输入密码',
    'userEmpty': '用户名不能为空',
    'pwdEmpty': '密码不能为空',
    'version': '版本号：',
    'company': '© 2016-2020 金现代信息产业股份有限公司'
  },
  'hussar-tenantManagement': {
    'tenantManagement': '租户管理',
    'selectAll': '全选',
    'systemName': '系统名称',
    'systemAccount': '系统账号',
    'createTime': '创建时间',
    'state': '状态',
    'operation': '操作',
    'disable': '禁用',
    'enable': '启用',
    'resetPassword': '重置密码',
    'newTenant': '新增租户',
    'resetSource': '重置数据源',
    'enterSystemName': '请输入系统名称',
    'enterSystemAccount': '请输入系统账号',
    'alreadyExist': '使用非默认数据库，将不会创建数据库，请确保数据库已存在！',
    'defaultDatabase': '是否默认数据库',
    'instanceName': '实例名',
    'dataBaseType': '数据库类型',
    'dataBaseIp': '数据库IP地址',
    'dataBasePort': '数据库端口号',
    'dataBaseName': '数据库名称',
    'dataBaseAddress': '数据库地址',
    'conectionUserName': '连接用户名',
    'connectionPassword': '连接密码',
    'connectionTest': '连接测试',
    'password': '输入密码',
    'enterPassword': '请输入密码',
    'confirmPassword': '确认密码',
    'enterPassword2': '请再次输入密码',
    'nameNotNull': '系统名称不能为空',
    'nameRule': '系统名称为1-32位非空字符',
    'accountNotNull': '系统账号不能为空',
    'accountRule': '系统账号必须是4-16位字母',
    'dataBaseNameNotNull': '数据库名不能为空',
    'dataBaseNameRule': '数据库名只能由数字字母下划线组成',
    'dataBaseAddressNotNull': '数据库地址不能为空',
    'ipAddressNotNull': 'ip地址不能为空',
    'ipRule': '请输入正确的ip(IPv4)地址',
    'portNotNull': '端口号不能为空',
    'portRule': '端口号只能由数字组成',
    'connectionNameNotNull': '连接用户名不能为空',
    'passwortNotNull': '密码不能为空',
    'passwordRule': '密码必须是6-16位非空字符',
    'confirmedToDeleteDataBase': '是否删除数据库用户及数据库？',
    'confirmedToEnable': '确定要启用吗？',
    'confirmedToDisable': '确定要禁用吗？',
    'dataFailed': '请求数据失败',
    'passwordWarning': '两次输入密码不一致！',
    'passwordNotice': '请输入正确的密码！',
    'connF': '数据库连接失败！',
    'resetS': '重置成功！',
    'resetF': '重置失败！',
    'addS': '新增成功！',
    'accountExict': '系统账号已存在！',
    'nameExist': '系统名称已存在！',
    'passWrong': '用户密码错误，数据库连接失败！',
    'connWrong2': '数据库连接失败！此连接为自定义连接，请确定已为当前连接创建好数据库及用户！',
    'databaseE': '数据库已存在！',
    'userE': '数据库用户已存在！',
    'modeE': '模式已存在！',
    'addF': '新增失败！',
    'startS': '启用成功！',
    'startF': '启用失败！',
    'disableS': '禁用成功！',
    'disableF': '禁用失败！'
  },
  'hussar-license': {
    'projectName': '项目名称',
    'licenseStartTime': '授权开始时间',
    'licenseEndTime': '授权结束时间',
    'licenseType': '授权类型',
    'applyLicense': '申请授权',
    'applyLicenseNotice': '点击此处链接获取正式授权',
    'applyLicenseStep1': '1、打开金企信→微应用→轻骑兵→授权管理→授权申请，填写相关信息后，扫描下方二维码并提交授权申请。',
    'applicationCode': '本机申请码为',
    'applyLicenseStep2': '2、申请审核完毕后，系统会将授权文件通过金企信以附件的形式发送至申请人，请注意查收。',
    'applyLicenseStep3': '3、上传授权文件中的hussar_v8.lic文件',
    'uploadFile': '上传文件',
    'applicationCodeError': '申请码有误，请按如下步骤操作',
    'applicationCodeErrorStep1': '1)Linux系统请检查"ifconfig"命令是否可执行，若不可执行请执行"yum install nXXX"进行安装。',
    'applicationCodeErrorStep2': '2)Windows系统请检查jdk(1.8)环境变量是否配置正确。',
    'applicationCodeErrorStep3': '3)检查完毕后请重启服务，若仍存在问题请联系平台组技术运维。',
    'customerService': '客  服：',
    'upload': '上传',
    'uploadText': '将文件拖到此处，或 ',
    'clickUpload': '点击上传',
    'licenseWarning1': '当前授权即将在  ',
    'licenseWarning2': '  到期。请尽快申请授权！',
    'dataFailed': '数据请求失败',
    'tableDataFailed': '表格数据请求失败',
    'licenseS': '授权成功！',
    'licenseW': '该授权文件无效！'
  },
  'hussar-manageLog': {
    'to': '至',
    'startTime': '开始日期',
    'endTime': '结束日期',
    'selectLogType': '请选择日志类型',
    'login': '登录',
    'passwordReset': '密码重置',
    'operationLog': '操作日志',
    'logType': '日志类型',
    'operationalBusinessMeaning': '操作业务含义',
    'executionStatus': '执行状态',
    'clientAddress': '客户端地址',
    'operatingTime': '操作时间',
    'logDetails': '日志详情',
    'userAccount': '用户账号',
    'userName': '用户名称',
    'log': '日志'
  },
  'hussar-personalCenter': {
    'systemInfo': '系统信息',
    'generalInformation': '一般信息',
    'dataBaseInfo': '数据库信息',
    'systemName': '系统名称:',
    'systemAccount': '系统账号:',
    'systemId': '系统ID:',
    'copy': '复制',
    'systemKey': '系统密钥:',
    'resetKey': '重置密钥',
    'multiTenant': '是否共库',
    'multiTenantInfo': '如果工作流和BASE平台使用同一个数据库，则选是，其余选否',
    'tianFu': '是否天斧:',
    'dataBaseType': '数据库类型:',
    'projectAddress': '项目地址:',
    'editDataBase': '修改数据库',
    'dataBaseName': '数据库名:',
    'ipAddress': 'IP地址:',
    'port': '端口:',
    'connectionUserName': '连接用户名:',
    'connectionPassword': '连接密码:',
    'copySuccess': '复制成功',
    'copyWarning': '该浏览器不支持自动复制',
    'dataBaseNameWarning': '数据库名只能由数字字母下划线组成',
    'dataBaseUserNameWarning': '数据库用户名只能由数字字母下划线组成',
    'passwordWarning': '密码不能为空',
    'ipWarning': '请输入正确的ip(IPv4)地址',
    'portWarning': '端口号只能由数字组成',
    'urlWarning': '请输入正确的url',
    'configurationInformationFailed': '请求配置信息失败',
    'projectAddressFailed': '获取项目地址失败',
    'confirmToResetKey': '确定要重置密钥吗？',
    'resetS': '重置成功！',
    'loginAgain': '请重新登录！',
    'resetF': '重置失败！',
    'connF': '数据库连接失败！',
    'dataBaseAddress': '数据库地址'
  },
  'hussar-modelEdit': {
    'processMana': '流程管理',
    'hello': '请输入流程名称',
    'processDescribe': '流程描述',
    'create': '创建时间',
    'editTime': '修改时间',
    'processKey': '流程标识',
    'processName': '流程名称',
    'look': '查看',
    'more': '更多操作',
    'release': '发布',
    'versionMana': '版本管理',
    'version': '版本',
    'clickUp': '点击上传',
    'toDrag': '将文件拖到此处，或',
    'noAddress': '尚未配置项目地址',
    'leadZIP': '请导入zip类型的文件',
    'zip': '模型.zip',
    'sureLead': '确定要导出这',
    'thisData': '条数据吗？',
    'sureLeadThis': '确定要导出这条数据吗？',
    'sureRelease': '确定要发布这条流程吗？',
    'inSucc': '导入成功！',
    'upWayWrong': '文件上传路径有误！',
    'inWrong': '导入失败！',
    'onGoing': '当前流程模型存在运行的流程实例，删除失败！',
    'relSuccess': '发布成功！',
    'setSu': '设置成功！',
    'notFind': '流程模型文件未找到！',
    'setFail': '设置失败！',
    'operationWidth': '300'
  },
  'hussar-process': {
    'inProcessName': '请输入流程名称',
    'inBusinessKey': '请输入业务主键',
    'chooseState': '请选择状态',
    'to': '至',
    'startData': '开始日期',
    'endData': '结束日期',
    'processInstance': '流程实例',
    'processName': '流程名称',
    'businessKey': '业务主键',
    'startTime': '启动时间',
    'endTime': '结束时间',
    'continueTime': '持续时间',
    'linkName': '环节名',
    'end': '结束',
    'state': '状态',
    'running': '运行中',
    'hanged': '已挂起',
    'reStart':'重启',
    'updateComment':'修改意见',
    'reStartS':'重启成功！',
    'done': '已完成',
    'hang': '挂起',
    'activation': '激活',
    'flowChart': '流程图',
    'terminate':'终止',
    'terminateS':'终止成功！',
    'terminateF':'终止失败！',
    'sureTerminate':'确定要终止吗？',
    'day': '天',
    'hour': '小时',
    'minute': '分',
    'second': '秒',
    'sureHang': '确定要挂起吗？',
    'sureActivation': '确定要激活吗？',
    'hangS': '挂起成功！',
    'hangF': '挂起失败！',
    'activationS': '激活成功！',
    'activationF': '激活失败！',
    'operationWidth': '200'
  },
  'hussar-task': {
    'inProcessName': '请输入流程名称',
    'chooseTimeoutState': '请选择超时状态',
    'startData': '开始日期',
    'endData': '结束日期',
    'to': '至',
    'chooseRunningState': '请选择运行状态',
    'taskManage': '任务管理',
    'processName': '流程名称',
    'nodeName': '节点名称',
    'receiver': '接收人',
    'startTime': '开始时间',
    'duringTime': '任务持续时间',
    'runningState': '运行状态',
    "timeoutState":"超时状态",
    'running': '运行中',
    'hanged': '已挂起',
    'whetherTimeout': '是否超时',
    'timeout': '已超时',
    'noTimeout': '未超时',
    'hang': '挂起',
    'activation': '激活',
    'flowChart': '流程图',
    'day': '天',
    'hour': '小时',
    'minute': '分',
    'second': '秒',
    'sureHang': '确定要挂起吗？',
    'sureActivation': '确定要激活吗？',
    'hangS': '挂起成功！',
    'hangF': '挂起失败！',
    'activationS': '激活成功！',
    'activationF': '激活失败！',
    'more': '更多操作',
    'jump': '自由跳转',
    'reject':'自由驳回',
    'jumpS': '自由跳转成功',
    'jumpE': '自由跳转失败',
    'edit': '修改参与者',
    'multUserOnlyOne': '会签任务参与者只能有一个',
    'add': '添加参与者',
    'addS': '添加成功',
    'addE': '添加失败',
    'approval': '直接审批',
    'approvalUserNull': '该任务参与者为空，无法直接审核',
    'approvalS': '审批成功',
    'approvalE': '审批失败',
    'urge': '催办',
    'urgeS': '催办成功',
    'urgeE': '催办失败',
    'selectNode': '请选择目标节点',
    'userNull': '请选择至少一位用户',
    'getNodeE': '获取任务节点失败',
    'activityNode': '流程节点',
    'duringTimeLabelWidth': '240px',
    'runningStateLabelWidth': '160px',
    'operationLabelWidth': '240px'
  },
  'hussar-modeling': {
    'versionManage': '版本管理',
    'look': '查看',
    'processName': '流程名称',
    'version': '版本',
    'releaseTime': '发布时间',
    'whetherMain': '是否主版本',
    'cancelMain': '取消主版本',
    'setMain': '设为主版本',
    'exportError': '菜单导出失败',
    'deleteSuccess': '删除成功！'
  },
  'hussar-adminHome': {
    'accessSystem': '接入系统',
    'processTemplate': '流程模板',
    'processInstance': '流程实例',
    'processTask': '流程任务',
    'obtainData': '数据获取'
  },
  'hussar-processCount': {
    'processTaskStatistics': '流程任务统计',
    'all': '全部',
    'thisWeek': '本周',
    'thisMonth': '本月',
    'thisYear': '全年',
    'processInstanceStatistics': '流程实例统计',
    'sevenDay': '近七日流程待办已办数量统计',
    'handleProcess': '办理流程',
    'toDOProcess': '待办流程',
    'proportionOfProcessInstances': '流程实例占比',
    'processInstTimeStatistics': '流程平均消耗时间及任务平均时间占比',
    'processTaskTimeStatistics': '流程任务平均消耗时间占比',
    'data': '数据',
    'total': '总量'
  },
  'hussar-tenantHome': {
    'processTemplate': '流程模板',
    'processInstance': '流程实例',
    'processTask': '流程任务',
    'overtimeTask': '超时任务'
  },
  'hussar-intergaceLog': {
    'to': '至',
    'startData': '开始日期',
    'endData': '结束日期',
    'orderState': '请选择执行状态',
    'success': '成功',
    'fail': '失败',
    'interfaceLog': '接口日志',
    'logType': '日志类型',
    'meaning': '操作业务含义',
    'performType': '执行状态',
    'clientAddress': '客户端地址',
    'operationTime': '操作时间',
    'logDetails': '日志详情',
    'userAccount': '用户账号',
    'userName': '用户名称',
    'performState': '执行状态',
    'log': '日志'
  },
  /* ----------画布--------------------*/
  'hussar-callActivity': {
    'componentParameters': '组件参数',
    'childProcessID': '子流程ID',
    'externalSubprocess': '外部子流程',
    'nameOfSubprocess': '子流程名称',
    'inputParameters': '输入参数',
    'outputParameters': '输出参数',
    'element': '调用元素',
    'description': '描述',
    'additionalManualActivity': '追加人工活动',
    'appendSingleGateway': '追加单一网关',
    'additionalEnd': '追加结束',
    'additionalAttachment': '追加连线'
  },
  'hussar-end': {
    'end': '结束'
  },
  'hussar-countersign': {
    'countersign': '会签节点',
    'permissionConfiguration ': '权限配置'
  },
  'hussar-exclusive': {
    'singleGateway': '单一网关',
    'gatewayID': '网关ID',
    'gatewayName': '网关名称'
  },
  'hussar-inclusive': {
    'multipleGateway': '多路网关',
    'gatewayID': '网关ID',
    'gatewayName': '网关名称'
  },
  'hussar-parallel': {
    'parallelGateway': '并行网关',
    'gatewayID': '网关ID',
    'gatewayName': '网关名称'
  },
  'hussar-polyLine': {
    'lineName': '连线名称',
    'gatewayID': '连接点修改'
  },
  'hussar-start': {
    'start': '开始',
    'formAddress': '表单地址',
    'formDetails': '表单详情'
  },
  'hussar-subprocess': {
    'subprocess': '子流程',
    'range': '子流程范围'
  },
  'hussar-user': {
    'manualActivity': '人工活动',
    'defaultCondition': '默认条件',
    'participants': '参与者',
    'ccPeople': '抄送人',
    'formAddress': '表单地址',
    'formDetails': '表单详情',
    'todoConfiguration': '待办配置',
    'taskListener': '任务监听器',
    'expirationDate': '到期时间',
    'copy': '复制',
    'paste': '粘贴',
    'delete': '删除'
  },
  'hussar-serviceTask': {
    'componentLabel': '服务组件',
    'taskConfiguration': '任务配置'
  },
  'hussar-topTool': {
    'left': '左对齐',
    'center': '水平居中对齐',
    'right': '右对齐',
    'top': '顶对齐',
    'vertical': '垂直居中对齐',
    'bottom': '底对齐',
    'handleOpinions': '办理意见',
    'clear': '清空',
    'willClear': '此操作将清空当前画布, 是否继续?',
    'clearCanvas': '清空画布',
    'success': '画布清除成功',

    'shortcuts': '快捷键',
    'validation': '校验',
    'workflowValidation': '工作流校验',
    'boforeValidation': '校验前请先保存并发布工作流',
    'selectDate': '选择日期',
    'no': '序号',
    'nodeName': '节点名称',
    'transactors': '办理人',
    'receivingTime': '接收时间',
    'handleTime': '办理时间',
    'handleWay': '办理方式',
    'validationSuccess': '校验成功',
    'viewTheFlowchart': '查看流程图',
    'save': '保存',
    'release': '发布',
    'revoke': '撤销',
    'redo': '重做',
    'copy': '复制',
    'paste': '粘贴',
    'delete': '删除',
    'selectAll': '全选',
    'moveUp': '上移',
    'moveDown': '下移',
    'moveLeft': '左移',
    'moveRight': '右移',
    'istop': '置顶',
    'setBottom': '置底',
    'enlargeCanvas': '放大画布',
    'upperRoller': 'Ctrl + 上滚轮',
    'zoomOutCanvas': '缩小画布',
    'lowerRoller': 'Ctrl + 下滚轮',
    'canvas': '画布100%',
    'fastMoving': '快速移动',
    'bringForward': '上移一层',
    'sendBackward': '下移一层'
  },

  'hussar-pendingEventModel': {
    'businessDetails': '业务详情',
    'todo': '双击左侧数据，进行待办配置',
    'ToDoConfiguration': '待办配置',
    'additionalConditions': '附加条件'
  },
  'hussar-participant-dept': {
    'search': '搜索部门',
    'none': '暂无部门数据哟~'
  },
  'hussar-participant-markedNode': {
    'search': '搜索已办节点',
    'none': '暂无可选择的已办节点哟~'
  },
  'hussar-participant-role': {
    'search': '搜索角色',
    'none': '暂无角色数据哟~',
    'searchFailed': '查询角色树失败',
    'exception': '查询角色树异常',
    'noRole': '当前选择不是角色'
  },
  'hussar-participant-user': {
    'search': '搜索用户',
    'none': '暂无用户数据哟~',
    'noUser': '当前选择不是用户'
  },
  'hussar-variable-businessVar': {
    'search': '搜索业务表变量',
    'none': '暂无业务表变量哟~'
  },
  'hussar-variable-contant': {
    'search': '搜索内置变量',
    'none': '暂无内置变量哟~',
    'dept': '发起人所属部门',
    'nextNode': '下一节点'
  },
  'hussar-variable-customVar': {
    'search': '搜索自定义变量',
    'add': '添加',
    'none': '暂无变量哟~',
    'new': '新增',
    'confirm': '上级参与者均删除此变量，确定删除吗？'
  },
  'hussar-variableInfo': {
    'note': '注：',
    'warning1': '当前操作会导致所有参与者的自定义变量改变',
    'warning2': '当前操作会导致上级参与者的自定义变量改变',
    'variableName': '变量名',
    'variableNameEn': '变量名(英文)',
    'variableAnnotation': '变量注释',
    'variableType': '变量类型',
    'string': '字符串',
    'number': '数字',
    'boolean': '布尔型',
    'create': '创建',
    'modifyVariables': '修改变量',
    'newVariables': '新增变量',
    'VariablesNameNotNUll': '变量名不能为空！',
    'noSpaces': '变量名内不能有空格！',
    'alreadyExist': '该类型变量名已有！'
  },
  'hussar-putPropModal': {
    'list': '参数列表',
    'resource': '资源',
    'expression': '资源表达式',
    'goal': '目标',
    'operation': '操作',
    'addProp': '没有配置参数,添加一个吧',
    'enterResource': '请输入一个资源',
    'enterExpression': '请输入一个资源表达式',
    'enterTarget': '请输入一个目标',
    'enterProp': '输入参数',
    'outProp': '输出参数',
    'di': '第',
    'warning': '行参数未配置正确！'
  },
  'hussar-processBinding': {
    'dataModel': '数据模型选择',
    'table': '当前模块对应表',
    'allTable': '所有表'
  },
  'hussar-conditionExpression': {
    'configureConditionalExpression': '配置条件表达式',
    'conditionalSelection': '条件选择',
    'conditionalExpression': '条件表达式',
    'input': '请输入',
    'warning': '条件表达式无法通过双击添加变量!'
  },
  'hussar-participant': {
    'participantConfiguration': '参与者配置',
    'role': '角色',
    'user': '用户',
    'dept': '部门',
    'doneNode': '已办节点',
    'variable': '变量',
    'variableTypeUnSupported': '变量类型不支持',
    'warning': '当前点击并非角色，不能加入当前条件中',
    'default': '默认条件',
    'function': '函数'
  },
  'hussar-participantConfigs': {
    'newCondition': '新建条件',
    'addParticipant': '双击左侧数据，添加参与者',
    'notConfigured': '未配置',
    'configuredError': '配置错误',
    'configureded': '已配置',
    'condition': '条件'
  },
  'hussar-formDetail': {
    'editName': '修改名称',
    'enter': '请输入页面路径',
    'detail': '表单详情',
    'duplicateName': '名称重复!'
  },
  'hussar-formAddress': {
    'address': '表单地址'
  },
  'hussar-formSelector': {
    'bpm': '工作流选择',
    'bpmSelect': '请选择工作流',
    'noBpm': '没有其它工作流',
    'allBpm': '工作流已经全部展示',
    'alreadyBpm': '此工作流已添加到列表中'
  },
  'hussar-conditionSelect': {
    'select': '请选择',
    'and': '且',
    'or': '或',
    'equal': '等于',
    'notEqualTo': '不等于',
    'contain': '包含',
    'doesNotContain': '不包含',
    'lessThan': '小于',
    'lessThanOrEqualTo': '小于等于',
    'greaterThan': '大于',
    'greaterThanOrEqualTo': '大于等于'
  },
  'hussar-flowCondition': {
    'flowCondition': '流条件',
    'warning': '条件表达式无法通过双击添加变量！',
    'warning2': '条件表达式格式不正确！'
  },
  'hussar-listenerModel': {
    'customEvent': '自定义事件',
    'searchCustomEvent': '搜索自定义事件',
    'addListener': '没有配置监听器,添加一个吧',
    'triggerEvent': '触发事件',
    'selectTriggerEvent': '请选择触发条件',
    'requestMethod': '请求方式',
    'selectRequestMethod': '请选择请求方式',
    'requestAddress': '请求地址',
    'inputRequestAddress': '请输入请求地址',
    'description': '描述',
    'inputDescription': '请输入相关描述',
    'taskListener': '任务监听器',
    'executionListener': '执行监听器',
    'warning': '行监听器请求地址数据格式有误！'
  },
  'hussar-carbonCopy': {
    'carbonCopy': '抄送人配置',
    'warning': '变量类型不支持',
    'messageRule1': '当前点击并非角色，不能加入当前条件中',
    'messageRule2': '当前点击并非用户，不能加入当前条件中'
  },

  /* bpmcomponent--editor*/
  'hussar-flowCarbonCopy': {
    'wrong': '配置错误',
    'participantConfiguration': '参与者配置',
    'condition': '默认条件'
  },
  'hussar-condition': {
    'wrong': '配置错误',
    'cannotConf': '不可配置',
    'conditionConf': '条件配置',
    'default': '默认流'
  },
  'hussar-counterSign': {
    'sign': '会签节点',
    'percent': '按比率完成',
    'count': '按个数完成'
  },
  'hussar-dueDate': {
    'sign': '设置截止时间',
    'month': '月',
    'day': '日',
    'hour': '时',
    'minute': '分'
  },
  'hussar-exeListener': {
    'listener': '个执行监听器'
  },
  'hussar-backlog': {
    'all': '全局待办配置'
  },
  'hussar-identity': {
    'process': '流程标识',
    'input': '请输入流程标识【字母开头】'
  },
  'hussar-params': {
    'count': '个输入参数'
  },
  'hussar-outParams': {
    'count': '个输入参数'
  },
  'hussar-flowParticipant': {
    'wrong': '配置错误',
    'condition': '默认条件'
  },
  'hussar-selector': {
    'already': '已选',
    'count': '个工作流'
  },
  'hussar-skipConf': {
    'skip': '跳过配置',
    'empty': '处理人为空',
    'repeat': '重复处理人'
  },
  'hussar-relevance': {
    'table': '流程关联表',
    'chooseTabel': '请选择流程关联表'
  },
  'hussar-taskListener': {
    'count': '个任务监听器'
  },
  'hussar-string': {
    'cancel': '取消配置'
  },
  'hussar-axeLogo': {
    'fineTuning': '流程微调',
    'save': '保存',
    'publish': '发布',
    'WORKFLOW': '工作流',
    'copy': '复制',
    'paste': '粘贴',
    'revoke': '撤销',
    'restore': '恢复',
    'massage1': '当前打开页面超过10个，建议关闭不常用页面',
    'massage2': '工作流未配置正确，请参考控制台提示信息操作！',
    'saveSuccess': '保存成功！',
    'saveFlowSuccess': '保存工作流成功',
    'savePageSuccess': '保存页面成功',
    'publishSuccess': '发布成功！',
    'publishFail': '发布失败',
    'restart': '重启超时！',
    'restartSuccess': '重启成功，是否打开预览',
    'cancel': '已取消'
  },
  'hussar-frame': {
    'processConfiguration': '流程配置'
  },
  'hussar-sideBtns': {
    'featureSet': '功能设置',
    'feature': '功能'
  },
  'hussar-index': {
    'processMana': '流程管理',
    'versionManagement': '版本管理',
    'instanceManagement': '实例管理',
    'taskManagement': '任务管理',
    'systemInformation': '系统信息',
    'logManagement': '日志管理',
    'theInterfaceLog': '接口日志',
    'theOperationLog': '操作日志',
    'functionManagement': '函数管理',
    'workflowDesigner': '工作流设计器',
    'haveNoRightToAccess': '无权访问',
    'tenantManagement': '租户管理',
    'authorizationManagement': '授权管理',
    'workFlow': '工作流平台'
  },
  'hussar-tagsView': {
    'homePage': '首页',
    'refresh': '刷新',
    'close': '关闭',
    'closeTheOther': '关闭其他',
    'closeAll': '关闭所有',
    'welcomeToUse': '欢迎使用'
  },
  'hussar-showflow': {
    'showflow': '流程图查看'
  },
  'hussar-flowfile': {
    'noPerson': '无办理人',
    'handle': '办理',
    'withdraw': '撤回',
    'reject': '驳回',
    'freeJump': '自由跳转',
    'read': '已阅',
    'termination': '终止'
  },
  'hussar-userFlow': {
    'start': '开始时间：',
    'end': '结束时间：',
    'transactors': '办理人：',
    'handleOpinions': '办理意见：',

    'receiver': '接收人：',
    'refuse': '驳回节点：',
    'revoke': '撤回节点：'
  },
  'hussar-startFlow': {
    'start': '开始',
    'end': '结束',
    'parallelGateway': '并行网关',
    'inclusiveGateway': '多路网关',
    'gateway': '单一网关',
    'subprocess': '外部子流程',
    'noCan': '不支持canvas',
    'done': '已完成',
    'in': '进行中',
    'notYet': '未到达',
    'overTime': '已超时',
    'reject': '驳回节点',
    'revoke': '撤回节点',
    'hang': '挂起',
    'handleOpinions': '办理意见'
  },
  'hussar-participantVariable': {
    'customVariables': '自定义变量',
    'built-inVariables': '内置变量'
  },
  'hussar-function': {
    'functionName': '函数名称',
    'inFunctionName':'请输入函数名称',
    'inBeanId':'请输入beanId',
    'functionMana': '函数管理',
    'createTime': '创建时间',
    'functionType': '函数查看',
    'funcAdd': '函数新增',
    'funcChange': '函数修改',
    "param":"参数",
    'addFunc': '增加参数',
    'paramName': '参数注释',
    'inParamName': '请输入参数注释',
    'paramIdent': '参数名',
    'inParamIdent': '请输入参数名',
    "configureParameter":"参数配置",
    'delWrong': '删除异常',
    'openWrong': '打开失败',
    'openError': '打开异常',
    'checkWrong': '查看失败',
    'checkError': '查看异常',
    'addSucc': '新增成功',
    'addWrong': '新增失败',
    // "addFail":"添加失败！（",
    // "unknowError":"未知错误",
    // "parenttheses":"）",
    // "changeFail":"修改失败！（",
    'check': '查看',
    'paramR1': '参数名不能包含特殊符号和中文',
    'paramR2': '参数名唯一性,不能重复',
    'funcR1': 'beanId不能包含特殊符号和中文',
    'paramR3': '函数BeanId最多可输入30个字符',
    'funcR2': '函数名称最多可输入30个字符',
    'funcR3': '参数名最多可输入30个字符',
    'paramR4': '参数注释最多可输入50个字符',
    'leadLcdpbpm': '请导入lcdpbpm类型的文件',
    'lcdpbpm': '函数.lcdpbpm',
    'typeWrong': '请导入正确格式的函数文件'
  },
  'hussar-variable-function': {
    'search': '搜索函数',
    'add': '添加',
    'none': '暂无函数哟~',
    'new': '新增',
    'addTitle': '新增函数',
    'editTitle': '修改函数',
    'builtInTitle': '内置变量',
    'customTitle': '自定义变量',
    'searchBuiltIn': '搜索内置变量',
    'searchCustom': '搜索自定义变量',
    'noneBuiltIn': '暂无内置变量哟~',
    'noneCustom': '暂无自定义变量哟~',
    'selectFunction': '函数选择',
    'pleaseSelectFunction': '请选择函数',
    'configureParameter': '参数配置',
    'cancel': '取消',
    'save': '保存',
    'create': '创建',
    'check': '请配置完整',
    'getFuncOptException': '获取函数请求异常',
    'getFuncOptItemException': '获取函数配置请求异常',
    'usedFunction': '函数已被使用！',
    'deletedFunction': '配置中的函数已被删除！'
  }
};


window.$hussarT = function(name){
  if(!name) return  '';
  let arr = name.split('.')
let res;
  if(arr.length == 1){
    res  =names[arr[0]];
  }
  if(arr.length == 2){
    res = names[arr[0]][arr[1]];
  }
  return res;
}
//获取轻骑兵用户id，为了区分用户id前面统一加100
function getHussarUserId(vueInstance){
  return '100' + vueInstance.$store.state.user.userId;
}

Vue.prototype.$getHussarUserId = getHussarUserId;
Vue.prototype.$hussarT = window.$hussarT;
